In [2]:
import cv2
import pandas as pd
import numpy as np


In [5]:
img = np.zeros((3,3))

print(img)

img_float32 = np.float32(img)

# image is in grey color as only one
# dimension is there

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# converting image to BGR format
img = cv2.cvtColor(img_float32,cv2.COLOR_GRAY2BGR)

print(img)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [7]:
# we can also represent with HSV(hue ,saturation,) color space
#  where hue has a range of (0-180) and different number of
# channels

img.shape
# returns number of row columns and channels of


(3, 3, 3)

In [9]:
# converting image format

image = cv2.imread('D:\corona trek\IMG_20200913_070740.jpg')
cv2.imwrite('mypic.png',image)

# info- by default imread() returns image in BGR format even if file
# is in greycolor . BGR format represents same color space as RGB
# byte value order is reversed.

True

In [10]:
# info -  we can specify the mode of imread()
# as IMREAD_ANYCOLOR = 4
#    IMREAD_ANYDEPTH = 2
#    IMREAD_COLOR = 1
#    IMREAD_GRAYSCALE =0 
#    IMREAD_LOAD_GDAL =8
#    IMREAD_UNCHANGED = -1

gray_image = cv2.imread('mypic.png',cv2.IMREAD_GRAYSCALE)
cv2.imwrite('mypicgrey.png',gray_image)

True

In [12]:
"""
Regardless of the mode, imread() discards any alpha channel (transparency). The
imwrite() function requires an image to be in the BGR or grayscale format with a
certain number of bits per channel that the output format can support. For example,
bmp requires 8 bits per channel, while PNG allows either 8 or 16 bits per channel

"""



'\nRegardless of the mode, imread() discards any alpha channel (transparency). The\nimwrite() function requires an image to be in the BGR or grayscale format with a\ncertain number of bits per channel that the output format can support. For example,\nbmp requires 8 bits per channel, while PNG allows either 8 or 16 bits per channel\n\n'

In [16]:
kapil_creates_image = np.array([[[2,3,1],[1,125,233],[233,56,56]],
                              [[125,106,123],[230,1,25],[255,255,255]],
                              [[255,255,255],[255,255,255],[102,145,78]]])

In [19]:
cv2.imwrite('kapil_creates_image.png',kapil_creates_image)

True